export const FIELDS = [
  {
    label: "Client Name",
    name: "name",
    type: "input",
    noValueError: "Please provide the first name",
    required: true,
  },
  {
    label: "Contact Number",
    name: "phone",
    type: "input",
    noValueError: "You must specify phone number",
    required: true,
  },
  {
    label: "Account Manager",
    name: "manager",
    type: "select",
    noValueError: "You must specify an Email",
    required: false,
  },
  {
    label: "About",
    name: "about",
    type: "textarea",
    noValueError: "You must specify an Email",
    required: false,
  },
  {
    label: "Fax",
    name: "fax",
    type: "input",
    noValueError: "You must specify an Email",
    required: false,
  },
  {
    // how did this user get created?
    label: "Source",
    name: "source",
    type: "select",
    noValueError: "Please select a source",
    required: false,
  },
  {
    label: "Billing Street",
    name: "street",
    type: "input",
    noValueError: "Please select a source",
    required: true,
  },
  {
    label: "Billing City",
    name: "city",
    type: "input",
    noValueError: "Please select a source",
    required: true,
  },
  {
    label: "Billing State",
    name: "state",
    type: "input",
    noValueError: "Please select a source",
    required: true,
  },
  {
    label: "Billing Zip",
    name: "zip",
    type: "input",
    noValueError: "Please select a source",
    required: true,
  },
  {
    label: "Billing Country",
    name: "country",
    type: "input",
    noValueError: "Please select a source",
    required: true,
  },
  {
    label: "Parent Client",
    name: "client",
    type: "input",
    noValueError: "Please select a source",
    required: false,
  },
];
